runtime: nodejs10
env: standard
instance_class: B1
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: '301'
  - url: .*
    script: auto
manual_scaling:
  instances: 1
network: {}